### ISSUE TITLE
Clarification sw 

### ISSUE THREAD

**Issue by asvny** [gokulkrishh/demo-progressive-web-app#1]
https://github.com/annamalai-saro/demo-progressive-web-app/blob/master/serviceWorker.js#L65-L69

I think the code should be 

``` js
caches.open(staticCache).then(function(cache) {
     cache.put(request, response.clone());
});

return response;
```

then at  https://github.com/annamalai-saro/demo-progressive-web-app/blob/master/serviceWorker.js#L56

`event.respondWith` is missing ...

Sorry  ..Please correct me if I am wrong ...

**Comment by gokulkrishh** [comment]
Ooopsy, I missed it. You are right on both the things

**Comment by asvny** [comment]
@gokulkrishh Okaay :+1:  ! BTW #pwa in bangalore was great :smile:

**Comment by gokulkrishh** [comment]
@annamalai-saro Good to know that you found it useful :+1:
