### ISSUE TITLE
How to create a push notification?

### ISSUE THREAD

**Issue by mbarmettler** [gokulkrishh/demo-progressive-web-app#16]
Hi,
thank you for sharing your project here, it helped me to come up with a PWA within minutes.
but now i was wondering on how to create push notifications with your demo app, just to see how it looks and feels...
can you provide me some inputs on how to use this project to create some demo pushs?
thank you

**Comment by gokulkrishh** [comment]
@mbarmettler Pls post ur questions in stack over flow. Issues in github are meant only for issue in the project.
