### ISSUE TITLE
How to Install

### ISSUE THREAD

**Issue by mehmetsarr** [gokulkrishh/demo-progressive-web-app#20]
Hello, thank you for the warehouse. Is there a tutorial for this pwa repository? Should I put all the files in the main directory? I'm trying to run this on a wordpress site. I do not know how to do it. Can you help me?

**Comment by gokulkrishh** [comment]
Hi, Its simple web application, how to install is given in readme file. If you don't know how to use it, post your question in stackoverflow for help.
