### ISSUE TITLE
Ionic PWA

### ISSUE THREAD

**Issue by jdnichollsc** [gokulkrishh/demo-progressive-web-app#4]
Hi man,

What do you think about to use Ionic 2 with Angular 2? :)

Regards, Nicholls

**Comment by gokulkrishh** [comment]
@jdnichollsc Hi, Sounds like a good idea to try with angular 2 as pwa. I will create a separate branch for it. I had a plan of doing pwa's with frameworks like angular 2, react (I have done 2 pwa), ember and others too.

**Comment by gokulkrishh** [comment]
Closing this since there are lots demo pwa for various frameworks.
