### ISSUE TITLE
silly question

### ISSUE THREAD

**Issue by JuanLuisClaure** [gokulkrishh/demo-progressive-web-app#6]
hey men. meaby it's the right place to ask.
i'm made my own framework to make progressive web apps
i'm super duper with how it works. but i have a issue about deploy
I'm made the same server-side render as you made.
but the question: how I ensure that when enter the url. www.foo.como/
is taking the server.js fisrt to render and not the index.html like it did usualy.?? 

Thanks

**Comment by gokulkrishh** [comment]
@JuanLuisClaure What I understood is you have site [abc.com](abc.com). So if you load the site, it should response from `server.js`. Thats means you have to run a server in your hosting and from the request, you should respond. Like express server for example.

**Comment by gokulkrishh** [comment]
@JuanLuisClaure Right now this app is hosted in github pages. You can try `now.sh` to deploy this app. Since I have configured `server.js` and in `package.json` to run the application.
