### ISSUE TITLE
cant work

### ISSUE THREAD

**Issue by hiren1612** [gokulkrishh/demo-progressive-web-app#8]
Hi,
when I test demo-progressive-web-app in my system with change Github Url in app.js page I can get some error and responce not getting?
Look my code is:

In App.js ->
    var name = username || 'gokulkrishh';
  //var url = 'https://api.github.com/users/' + name;
    var url = 'https://test.com';
		
any Idea?

Thanks

**Comment by gokulkrishh** [comment]
@hiren1612 I see. `var url = 'https://api.github.com/users/' + name;` is github API to fetch user profile. `var url = 'https://test.com';` seems to be a fake URL. Thats the reason.

**Comment by gokulkrishh** [comment]
@hiren1612 Provide a working URL. It will work. Closing this issue in favour of above comments. Thanks
