### ISSUE TITLE
Github pages demo 

### ISSUE THREAD

**Issue by maxjf1** [gokulkrishh/demo-progressive-web-app#9]
Is possible to make an github pages demo?

**Comment by gokulkrishh** [comment]
@maxjf1 demo is in GitHub pages!!

**Comment by maxjf1** [comment]
Sorry, didnt find it on readme :P

**Comment by nimitbhargava** [comment]
@maxjf1 
https://gokulkrishh.github.io/demo-progressive-web-app/

**Comment by gokulkrishh** [comment]
@nimitbhargava Thanks. @maxjf1 Since this answers your question. Closing this issue.
